name: Build and Publish
on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    name: Build and Publish
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: zulu
          java-version: 17
      - name: Install GPG secret key
        run: |
          # Install gpg secret key
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG
      - name: Maven Sign and Publish
        env:
          GITHUB_ACTOR: '3dwardCh3nG'
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEY_NAME: ${{ secrets.OSSRH_GPG_KEY_NAME }}
          GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: |
          mvn -X -B deploy -Daether.checksums.algorithms="MD5,SHA-1,SHA-256,SHA-512" -P publish --settings=${{ github.workspace }}/.mvn/settings.xml
      - uses: actions/upload-artifact@v3.1.3
        if: always()
        with:
          name: Java Artifacts
          path: ${{ github.workspace }}/**/target/*.*