name: Build and Publish
on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    name: Build and Publish
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: zulu
          java-version: 17
      - name: Maven Sign and Publish
        env:
          GITHUB_ACTOR: '3dwardCh3nG'
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mvn -X -B org.apache.maven.plugins:maven-gpg-plugin:3.1.0:sign \
            -Dgpg.keyname=${{ secrets.OSSRH_GPG_KEY_NAME }} \
            -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
#            -Dgpg.executable="${{ github.workspace }}/scripts/runGPG.sh" \
#            deploy \
#            -DaltDeploymentRepository=${{ secrets.DEPLOYMENT_REPOSITORY_ID }}::${{ secrets.DEPLOYMENT_REPOSITORY_URL }} \
#            --settings=${{ github.workspace }}/.mvn/settings.xml
      - uses: actions/upload-artifact@v3.1.3
        if: always()
        with:
          name: Java Artifacts
          path: ${{ github.workspace }}/**/target/*.*